[project]
name = "mc-srv-manager"
version = "0.1.0"
description = "Minecraft Server Manager"
authors = [
    { name = "Your Name", email = "your.email@example.com" }
]
requires-python = ">=3.8"
dependencies = [
    "beautifulsoup4==4.13.4",
    "blinker==1.9.0",
    "bs4==0.0.2",
    "certifi==2025.4.26",
    "charset-normalizer==3.4.1",
    "click==8.1.8",
    "Flask==3.1.0",
    "gamuLogger==3.1.1",
    "idna==3.10",
    "itsdangerous==2.2.0",
    "Jinja2==3.1.6",
    "MarkupSafe==3.0.2",
    "requests==2.32.3",
    "soupsieve==2.7",
    "typing_extensions==4.13.2",
    "urllib3==2.4.0",
    "Werkzeug==3.1.3",
    "dnspython==2.7.0",
    "eventlet==0.39.1",
    "greenlet==3.2.1",
]

[project.scripts]
mc-srv-manager = "mc_srv_manager.__main__:main"

[tool.setuptools]
packages = ["mc_srv_manager"]
package-data = { "mc_srv_manager" = ["client/**"] }
include-package-data = true